//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielaMundial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuentroGrupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuentroGrupo()
        {
            this.EncuentroGrupoVati = new HashSet<EncuentroGrupoVati>();
            this.EncuentroGrupoVati1 = new HashSet<EncuentroGrupoVati>();
        }
    
        public int idEncGrup { get; set; }
        public int idMundial { get; set; }
        public int idEncuentro { get; set; }
        public int idEquiGrup { get; set; }
        public int golesEncuentros { get; set; }
        public double puntosEncuentro { get; set; }
        public Nullable<System.DateTime> fechaEncuentro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuentroGrupoVati> EncuentroGrupoVati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuentroGrupoVati> EncuentroGrupoVati1 { get; set; }
    }
}
