//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielaMundial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuentroGrupoVatii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuentroGrupoVatii()
        {
            this.Vaticinio = new HashSet<Vaticinio>();
        }
    
        public int idEncGruVati { get; set; }
        public int idEncuentro { get; set; }
        public int idEncGrup { get; set; }
        public int PrediGol { get; set; }
    
        public virtual EncuentroGrupo EncuentroGrupo { get; set; }
        public virtual Encuentros Encuentros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaticinio> Vaticinio { get; set; }
    }
}
