//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielaMundial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoGrupo
    {
        public int idEquiGrup { get; set; }
        public int idMundial { get; set; }
        public int idGrupo { get; set; }
        public int idEquipo { get; set; }
        public int goles { get; set; }
        public double puntos { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Mundial Mundial { get; set; }
    }
}
