//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielaMundial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitados
    {
        public int idInvitados { get; set; }
        public int idAdministrador { get; set; }
        public int idPersona { get; set; }
        public int idSolicitud { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Solicitudes Solicitudes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
