//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielaMundial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mundial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mundial()
        {
            this.EquipoGrupo = new HashSet<EquipoGrupo>();
            this.Quiniela = new HashSet<Quiniela>();
        }
    
        public int idMundial { get; set; }
        public string mundial1 { get; set; }
        public Nullable<System.DateTime> fechar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoGrupo> EquipoGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiniela> Quiniela { get; set; }
    }
}
