//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielaMundial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuinielaVaticinio
    {
        public int idQuiVati { get; set; }
        public int idQui { get; set; }
        public int idPersona { get; set; }
        public int idVati { get; set; }
        public double puntosQuiniela { get; set; }
        public Nullable<System.DateTime> fechaQuiVati { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Quiniela Quiniela { get; set; }
        public virtual Vaticinio Vaticinio { get; set; }
    }
}
