//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielaMundial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaticinio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaticinio()
        {
            this.QuinielaVaticinio = new HashSet<QuinielaVaticinio>();
        }
    
        public int idVati { get; set; }
        public int idPersona { get; set; }
        public int idQui { get; set; }
        public int idEncuentro { get; set; }
        public int idEncGruVati { get; set; }
        public int idVatiEstado { get; set; }
        public double puntosVati { get; set; }
        public Nullable<System.DateTime> fechaVati { get; set; }
    
        public virtual EncuentroGrupoVati EncuentroGrupoVati { get; set; }
        public virtual Encuentros Encuentros { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Quiniela Quiniela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuinielaVaticinio> QuinielaVaticinio { get; set; }
        public virtual VatiEstado VatiEstado { get; set; }
    }
}
